name       : grim
version    : 1.4.1
release    : 3
source     :
    - https://git.sr.ht/~emersion/grim/archive/v1.4.1.tar.gz : 5ed8e70fcd83a7e203e92d34dbb82a1342d3f13ad98a6b0310cc97e1a9342ded
license    : MIT
homepage   : https://wayland.emersion.fr/grim/
component  : multimedia.graphics
summary    : Grab images from a Wayland compositor
description: |
    Grab images from a Wayland compositor
builddeps  :
    - pkgconfig(libjpeg)
    - pkgconfig(pixman-1)
    - pkgconfig(libpng)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
rundeps    :
    - slurp
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
